/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.informatica.proyecto1.presentacion;

import java.awt.Canvas;
import javax.swing.JSlider;

/**
 *
 * @author harol
 */
public class Vista extends javax.swing.JFrame {
    
    //VARIABLES
    private Controlador control;
    private Modelo modelo;

    
    //GETTERS
    public Modelo getModelo() {
        return modelo;
    }
    
    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }
    
    /**
     * Constructor de la vista 
     * @param m 
     */
    public Vista(Modelo m) {
        modelo = m;
        initComponents();
        asignarEventos();
    }

    
    
    private void asignarEventos() {
        sldFalangeDigIzq.addChangeListener(getControl());
        sldFalangeDigDer.addChangeListener(getControl());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCanvas = new javax.swing.JPanel();
        lienzo = new java.awt.Canvas();
        PanelControles = new javax.swing.JPanel();
        sldFalangeDigIzq = new javax.swing.JSlider();
        sldFalangeDigDer = new javax.swing.JSlider();
        lblFalanges = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 350));

        PanelCanvas.setBackground(new java.awt.Color(255, 255, 255));
        PanelCanvas.setPreferredSize(new java.awt.Dimension(300, 300));

        lienzo.setBackground(new java.awt.Color(204, 204, 204));
        lienzo.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout PanelCanvasLayout = new javax.swing.GroupLayout(PanelCanvas);
        PanelCanvas.setLayout(PanelCanvasLayout);
        PanelCanvasLayout.setHorizontalGroup(
            PanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCanvasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelCanvasLayout.setVerticalGroup(
            PanelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCanvasLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        lienzo.getAccessibleContext().setAccessibleName("");

        PanelControles.setBackground(new java.awt.Color(255, 255, 255));
        PanelControles.setPreferredSize(new java.awt.Dimension(200, 300));

        sldFalangeDigIzq.setMaximum(180);
        sldFalangeDigIzq.setMinimum(-180);
        sldFalangeDigIzq.setPaintLabels(true);
        sldFalangeDigIzq.setPaintTicks(true);
        sldFalangeDigIzq.setSnapToTicks(true);
        sldFalangeDigIzq.setToolTipText("Falange Dig Izq");
        sldFalangeDigIzq.setValue(0);
        sldFalangeDigIzq.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sldFalangeDigIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldFalangeDigIzq.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        sldFalangeDigIzq.setName("Falange Dig Izq"); // NOI18N

        sldFalangeDigDer.setMaximum(180);
        sldFalangeDigDer.setMinimum(-180);
        sldFalangeDigDer.setPaintLabels(true);
        sldFalangeDigDer.setPaintTicks(true);
        sldFalangeDigDer.setSnapToTicks(true);
        sldFalangeDigDer.setToolTipText("Falange Dig Izq");
        sldFalangeDigDer.setValue(0);
        sldFalangeDigDer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sldFalangeDigDer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldFalangeDigDer.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        sldFalangeDigDer.setName("Falange Dig Izq"); // NOI18N

        lblFalanges.setText("Falanges Digitales:");

        javax.swing.GroupLayout PanelControlesLayout = new javax.swing.GroupLayout(PanelControles);
        PanelControles.setLayout(PanelControlesLayout);
        PanelControlesLayout.setHorizontalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addComponent(sldFalangeDigIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldFalangeDigDer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addComponent(lblFalanges)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelControlesLayout.setVerticalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblFalanges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sldFalangeDigDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldFalangeDigIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        sldFalangeDigIzq.getAccessibleContext().setAccessibleName("Falange Dig Izq");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelControles, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //GETTERS DE LOS COMPONENTES DEL FRAME
    public Canvas getLienzo() {
        return lienzo;
    }

    public JSlider getSldrFalangeDigIzq() {
        return sldFalangeDigIzq;
    }

    public JSlider getSldFalangeDigDer() {
        return sldFalangeDigDer;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCanvas;
    private javax.swing.JPanel PanelControles;
    private javax.swing.JLabel lblFalanges;
    private java.awt.Canvas lienzo;
    private javax.swing.JSlider sldFalangeDigDer;
    private javax.swing.JSlider sldFalangeDigIzq;
    // End of variables declaration//GEN-END:variables
}
